"""time and date setup

Revision ID: f41f09ee1903
Revises: 
Create Date: 2025-04-04 01:00:05.284568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f41f09ee1903'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('availability_start', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('availability_end', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('days_available', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.drop_column('days_available')
        batch_op.drop_column('availability_end')
        batch_op.drop_column('availability_start')

    # ### end Alembic commands ###
